package icecite.parse;

import java.io.File;
import java.nio.file.Path;

import com.google.inject.assistedinject.Assisted;
import com.google.inject.assistedinject.AssistedInject;

import icecite.exception.IceciteException;
import icecite.models.PdfCharacter;
import icecite.models.PdfCharacterList.PdfCharacterListFactory;
import icecite.models.PdfDocument;
import icecite.models.PdfDocument.PdfDocumentFactory;
import icecite.models.PdfFigure;
import icecite.models.PdfPage;
import icecite.models.PdfShape;
import icecite.parse.filter.PdfCharacterFilter;
import icecite.parse.filter.PdfFigureFilter;
import icecite.parse.filter.PdfShapeFilter;
import icecite.parse.stream.HasPdfStreamParserHandlers;
import icecite.parse.stream.PdfStreamParser;
import icecite.parse.stream.PdfStreamParser.PdfStreamParserFactory;
import icecite.parse.translate.DiacriticsTranslator;
import icecite.parse.translate.LigaturesTranslator;

/**
 * A plain implementation of {@link PdfParser}.
 *
 * @author Claudius Korzen
 */
public class PlainPdfParser implements PdfParser, HasPdfStreamParserHandlers {
  /**
   * The instance of PdfStreamParser.
   */
  protected PdfStreamParserFactory streamParserFactory;

  /**
   * The factory to create instances of PdfDocument.
   */
  protected PdfDocumentFactory documentFactory;

  /**
   * The factory to create instances of PdfCharacterList.
   */
  protected PdfCharacterListFactory characterListFactory;

  /**
   * The PDF document.
   */
  protected PdfDocument pdfDocument;

  /**
   * The current page.
   */
  protected PdfPage page;

  /**
   * The predecessor of the current character (needed to translate diacritics).
   */
  protected PdfCharacter prevChar;

  /**
   * The predecessor of prevCharacter (needed to translate diacritics).
   */
  protected PdfCharacter prevPrevChar;

  /**
   * The boolean flag to indicate whether ligatures should be translated or not.
   */
  protected boolean translateLigatures;

  /**
   * The boolean flag to indicate whether characters with diacritics should be
   * translated or not.
   */
  protected boolean translateDiacritics;

  // ==========================================================================
  // Constructors.

  /**
   * Creates a new PDF parser.
   * 
   * @param streamParserFactory
   *        The PDF stream parser.
   * @param docFactory
   *        The factory to create instances of PdfDocument.
   * @param characterListFactory
   *        The factory to create instances of PdfCharacterList.
   */
  @AssistedInject
  public PlainPdfParser(PdfStreamParserFactory streamParserFactory,
      PdfDocumentFactory docFactory,
      PdfCharacterListFactory characterListFactory) {
    this(streamParserFactory, docFactory, characterListFactory, true, true);
  }

  /**
   * Creates a new PDF parser.
   * 
   * @param pdfStreamParserFactory
   *        The PDF stream parser.
   * @param pdfDocumentFactory
   *        The factory to create instances of PdfDocument.
   * @param characterListFactory
   *        The factory to create instances of PdfCharacterList.
   * @param translateLigatures
   *        The boolean flag to indicate whether ligatures should be translated
   *        or not.
   * @param translateDiacritics
   *        The boolean flag to indicate whether characters with diacritics
   *        should be translated or not.
   */
  @AssistedInject
  public PlainPdfParser(PdfStreamParserFactory pdfStreamParserFactory,
      PdfDocumentFactory pdfDocumentFactory,
      PdfCharacterListFactory characterListFactory,
      @Assisted("translateLigatures") boolean translateLigatures,
      @Assisted("translateDiacritics") boolean translateDiacritics) {
    this.streamParserFactory = pdfStreamParserFactory;
    this.documentFactory = pdfDocumentFactory;
    this.characterListFactory = characterListFactory;
    this.translateLigatures = translateLigatures;
    this.translateDiacritics = translateDiacritics;
  }

  // ==========================================================================
  // Parse methods.

  @Override
  public PdfDocument parsePdf(Path pdf) throws IceciteException {
    return parsePdf(pdf != null ? pdf.toFile() : null);
  }

  @Override
  public PdfDocument parsePdf(File pdf) throws IceciteException {
    PdfStreamParser streamParser = this.streamParserFactory.create(this);

    // Parse the PDF file.
    streamParser.parsePdf(pdf);

    // Return the PdfDocument generated by the handler methods below.
    return this.pdfDocument;
  }

  // ==========================================================================
  // Getter methods.

  @Override
  public boolean isTranslateLigatures() {
    return this.translateLigatures;
  }

  @Override
  public boolean isTranslateDiacritics() {
    return this.translateDiacritics;
  }

  // ==========================================================================
  // Setter methods.

  @Override
  public void setIsTranslateLigatures(boolean translateLigatures) {
    this.translateLigatures = translateLigatures;
  }

  @Override
  public void setIsTranslateDiacritics(boolean translateDiacritics) {
    this.translateDiacritics = translateDiacritics;
  }
  
  // ==========================================================================
  // Handler methods.

  @Override
  public void handlePdfFileStart(File pdf) {
    // Create a new PDF document.
    this.pdfDocument = this.documentFactory.create(pdf);
  }

  @Override
  public void handlePdfFileEnd(File pdf) {
    // Nothing to do so far.
  }

  @Override
  public void handlePdfPageStart(PdfPage page) {
    this.page = page;
  }

  @Override
  public void handlePdfPageEnd(PdfPage page) {
    this.pdfDocument.addPage(page);
  }

  @Override
  public void handlePdfCharacter(PdfCharacter chaar) {
    // Check if the character is a ligature. If so, translate it.
    if (isTranslateLigatures()) {
      LigaturesTranslator.translateLigature(chaar);
    }

    // Check if the character is a diacritic. If so, translate it.
    // In most cases, diacritic characters are represented in its decomposed
    // form. For example, "è" may be represented as the two characters "'e" or
    // "e'". To merge such characters the base character must be followed by
    // the diacritic: "e'" implicitly. To maintain this order, decide to which
    // base character a diacritic belongs and merge them together.

    // To decide to which character the diacritic belongs, we have to wait for
    // the character after the diacritic, so we check if the previous character
    // is a diacritic and compare the horizontal overlap between (a) the
    // diacritic and the character "in front" of the character
    // (prePreviousCharacter) and (b) the diacritic and the character "behind"
    // the character (the current character).
    if (isTranslateDiacritics()) {
      DiacriticsTranslator.translate(this.prevChar, this.prevPrevChar, chaar);
    }

    if (!PdfCharacterFilter.filterPdfCharacter(chaar)) {
      this.page.addCharacter(chaar);
      this.pdfDocument.addCharacter(chaar);
    }

    this.prevPrevChar = this.prevChar;
    this.prevChar = chaar;
  }

  @Override
  public void handlePdfFigure(PdfFigure figure) {
    if (PdfFigureFilter.filterPdfFigure(figure)) {
      return;
    }
    this.page.addFigure(figure);
    this.pdfDocument.addFigure(figure);
  }

  @Override
  public void handlePdfShape(PdfShape shape) {
    if (PdfShapeFilter.filterPdfShape(shape)) {
      return;
    }
    this.page.addShape(shape);
    this.pdfDocument.addShape(shape);
  }
}
